name: FORD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  documentation:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.10]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install FORD
      if: contains( matrix.os, 'ubuntu' )
      run: |
        python -m pip install --upgrade pip
        pip install ford
    
    - name: Build FORD documentation
      run: ford ./ford.yml

    - name: Deploy documentation
      uses: JamesIves/github-pages-deploy-action@v4.6.8
      with:
        branch: gh-pages
        folder: doc